---
- name: carregar necessarios
  include_vars: ../vars/necessarios.yml

- name: pacotes no pacstrap
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in necessarios %}
        {{ pkg | quote }}
      {% endfor %}
  async: 3600
  poll: 15

- name: Carregar plugin externo
  include_vars: "{{ plugin }}"
  when: 
    - plugin is defined
    - accept in ['y', 'Y', 'yes', 'YES', 'Yes', '', 's', 'S', 'sim', 'SIM', 'Sim']
    - plugin is file

- name: Instalando plugin settado
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in pacotes %}
        {{ pkg | quote }}
      {% endfor %}
  when: 
    - plugin is defined
    - accept in ['y', 'Y', 'yes', 'YES', 'Yes', '', 's', 'S', 'sim', 'SIM', 'Sim']
    - plugin is file
  async: 3600
  poll: 15

