---
- name: carregar necessarios
  include_vars: ../vars/necessarios.yml

- name: pacotes no pacstrap
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in sistema %}
        {{ pkg | quote }}
      {% endfor %}

- name: Carregar plugin externo
  include_vars: "{{ plugin }}"
  when: plugin is defined and accept in ['y', 'Y', 'yes', 'YES', 'Yes', '', 's', 'S', 'sim', 'SIM', 'Sim']

- name: Instalando plugin settado
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in pacotes %}
        {{ pkg | quote }}
      {% endfor %}
  when: plugin is defined and accept in ['y', 'Y', 'yes', 'YES', 'Yes', '', 's', 'S', 'sim', 'SIM', 'Sim']

