---
- name: setup do reflector
  ansible.builtin.shell: ../scripts/reflector.sh

- name: pacotes no pacstrap
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in necessarios %}
        {{ pkg | quote }}
      {% endfor %}
