- name: Carregar plugin externo
  include_vars: "{{ plugin }}"
  when: plugin is defined and accept in ['y', 'Y', 'yes', 'YES', 'Yes', '', 's', 'S', 'sim', 'SIM', 'Sim']

- name: Instalar sistema base e pacotes de plugin
  vars:
    pacotes_plugin: "{{ pacotes | default([]) }}"
  
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in sistema + pacotes_plugin %}
        {{ pkg | quote }}
      {% endfor %}
  changed_when: true
