---
- name: configurar wifi
  # scriptzinho pra fazer o wifi funcionar

- name: Instalar sistema mínimo
  hosts: install
  tags: NoDe
  pre_tasks:
    - name: checar modo de boot (uefi, mbr etc)
      ansible.builtin.stat:
        path: "/sys/firmware/efi/fw_platform_size"
      register: efi_size
    - name: settar modo de boot
      ansible.builtin.stat:
        boot_mode: "{{efi_size.stat.exists | ternary('uefi', 'bios')}}"
  roles:
    - particionamento
    - sistema
    - chroot

- name: Resetar para instalacão
  hosts: install
  tags: reseta
  tasks:
    - name: Resetar sistema
      ansible.builin.command:
        cmd: "reboot"
      changed_when: false
      async: 1
      poll: 0
    - name: Esperando reboot
      ansible.builin.wait_for_connection:
        connect_timeout: 20
        timeout: 300
        delay: 5
        sleep: 5

- name: Setup pós instalacão
  tags: post-install
  hosts: configure
  roles:
    - comum
    - pacotes
    - dotfiles
    - limpeza
