- name: gerar fstab
  ansible.builtin.shell:
    cmd: "genfstab -U {{ fsroot }} >> {{ fsroot }}/etc/fstab"

- name: configurar a região
  ansible.builtin.shell: roles/chroot/scripts/regiao.sh

- name: configurar a personalização
  ansible.builtin.shell: roles/chroot/scripts/personalizacao.sh

- name: configurar o refind
  ansible.builtin.shell: roles/chroot/scripts/bootloader.sh
