- name: gerar fstab
  ansible.builtin.shell:
    cmd: "genfstab -U {{ fsroot }} >> {{ fsroot }}/etc/fstab"

- name: configurar a região
  ansible.builtin.shell: ../scripts/regiao.sh

- name: configurar a personalização
  ansible.builtin.shell: ../scripts/personalizacao.sh

- name: configurar o refind
  ansible.builtin.shell: ../scripts/bootloader.sh
