- name: Formatação de partição root
  ansible.builtin.filesystem:
    fstype: "{{ formato }}"
    dev: "{{ root }}"
  when: formato is defined and root is defined

- name: Formatação de partição home
  ansible.builtin.filesystem:
    fstype: ext4
    dev: "{{ home }}"
  when: home is defined

- name: Formatação de partição swap
  ansible.builtin.filesystem:
    fstype: swap
    dev: "{{ swap }}"
  when: swap is defined

- name: Formatação de partição boot
  ansible.builtin.filesystem:
    fstype: vfat
    dev: "{{ boot }}"
  when: boot is defined

- name: ativar swap
  ansible.builtin.command:
    cmd: swapon {{ swap }}
  when: swap is defined

- name: ativar root
  ansible.builtin.mount:
    path: /mnt
    src: "{{ root }}"
    fstype: "{{ formato }}"
    state: mounted
  when: root is defined and formato is defined

- name: ativar home
  ansible.builtin.mount:
    path: /mnt/home
    src: "{{ home }}"
    fstype: ext4
    state: mounted
  when: home is defined and root is defined and formato is defined

- name: ativar boot
  ansible.builtin.mount:
    path: /mnt/boot
    src: "{{ boot }}"
    fstype: vfat
    state: mounted
  when: boot is defined and formato is defined and root is defined
